name: glados checkin

on:
  push:
    branches: [main,master]
  schedule:
    - cron: '15 10 * * *'
jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'clone repo'
        uses: actions/checkout@v3.3.0
      - name: 'run script'
        run: echo "RESULT=$(python3 ./glados_check.py)" >> $GITHUB_ENV
      - name: 'send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.qq.com
          server_port: 456
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: glados 签到(${{env.RESULT}})
          body: hello world
          to: ${{secrets.MAIL_TO}}
          from: github actions
          # content_type: text/html
