name:'glados checkin'

on:
  schedule:
    - cron: '15 10 * * *'
jobs:
  bot:
    runs-on:ubuntu-latest
    steps:
    # copy git仓库到虚拟机上
    - name: 'clone repo'
    uses: actions/checkout@v1
    # 执行仓库中脚本
    - name: 'run script'
    run: echo "RESULT=$(python3 ./glados_check.py)" >> $GITHUB_ENV
    # 发送邮件
    - name: 'send mail'
    uses: dawidd6/action-send-mail@master
    with:
      server_address: smtp.qq.com
      server_port: 456
      username: ${{secrets.MAIL_USERNAME}}
      password: ${{secrets.MAIL_PASSWORD}}
      subject: glados 签到
      body: file://result.html
      to: ${{secrets.MAIL_TO}}
      from: github actions
      content_type: text/html
      

      
